### ISSUE TITLE
Schduled transitions does not enable for all content types if installed first

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_workflows#25]
The module scheduled transitions was installed, but not enabled for any node types. 
This is on a fresh install (`lando drush si localgov; lando drush en localgov_demo; lando drush en localgov_review_date`) so I think that needs to be either documented in the readme, or if workflows is switched on add all the localgov content types to scheduled transitions.

_Originally posted by @andybroomfield in https://github.com/localgovdrupal/localgov_workflows/issues/18#issuecomment-938841996_

@finnlewis stated that it is in the .install file, but not in the .installed hook. I think localgov_workflows gets switched on when installing localgov_demo? but before all the content types.

**Comment by budda** [comment]
Just experienced this myself.

It was enabled for the Alert Banner content type. Possibly because this was enabled after the Scheduled Transitions module was enabled?

I don't think reviewing should be enabled on all types possible though.
No point reviewing News stories in the future for example, or service landing pages.

**Comment by stephen-cox** [comment]
There was an issue with the automatic configuration of Scheduled Transitions. Both this module and Alert Banner automatically configure the enabled entity types when the respective module is enabled, but they wiped out the configuration of the other module. The code in Alert Banner was running after the code in this module, so the content types weren't being enabled.

This should be fixed with #41 and https://github.com/localgovdrupal/localgov_alert_banner/pull/212
